#!/bin/python3

# Declare second integer, double, and String variables.

# Read and save an integer, double, and String to your variables.

# Print the sum of both integer variables on a new line.

# Print the sum of the double variables on a new line.

# Concatenate and print the String variables on a new line
# The 's' variable above should be printed first.

var1 = input()
var2 = input()
var3 = input()

print(i + int(var1))
print(d + float(var2))
print(s + str(var3))
